name: Test Build

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: '1.24'

    - name: Install NSIS
      run: choco install nsis -y

    - name: Build
      env:
        CGO_ENABLED: 0
      run: |
        go build -ldflags="-s -w -H=windowsgui" -trimpath -o focusd.exe ./cmd/focusd

    - name: Build NSIS Installer
      run: |
        makensis /DVERSION=test-build installer.nsi

    - name: Upload Artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: focusd-test-build
        path: |
          focusd.exe
          focusd_setup.exe
        retention-days: 5
