name: Test Build

on:
  push:
    branches: ["test"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Install NSIS
        run: |
          choco install nsis -y
          echo "C:\Program Files (x86)\NSIS" >> $env:GITHUB_PATH

      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w -H=windowsgui" -trimpath -o focusd.exe ./cmd/focusd

      - name: Build NSIS Installer
        run: |
          makensis /DVERSION=test-build installer.nsi

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: focusd-test-build
          path: |
            focusd.exe
            focusd_setup.exe
          retention-days: 5
