name: Test Build

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install NSIS
      run: choco install nsis -y

    - name: Build
      run: |
        go build -ldflags="-s -w -H=windowsgui" -trimpath -o focusd.exe ./cmd/focusd

    - name: Build NSIS Installer
      run: |
        makensis /DVERSION=test-build installer.nsi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: focusd-test-build
        path: |
          focusd.exe
          focusd_setup.exe
        retention-days: 5
